In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from db import engine

plt.rcParams["figure.figsize"] = (15, 6)
sns.set_style('whitegrid')

In [2]:
with engine.connect() as conn:
    df = pd.read_sql("select * from avg_daily_stats", conn)

In [3]:
df.head()

,city,state,observed_date,avg_temperature,avg_feels_like,avg_humidity,avg_pressure,avg_wind_speed
0,Albuquerque,NM,2023-01-01,6.05,3.20,67.92,840.69,5.39
1,Albuquerque,NM,2023-01-02,5.50,1.98,72.71,840.31,10.62
2,Albuquerque,NM,2023-01-03,2.64,-1.64,55.58,844.99,9.97
3,Albuquerque,NM,2023-01-04,2.03,-1.60,65.04,849.82,6.55
4,Albuquerque,NM,2023-01-05,1.48,-2.24,61.17,850.56,6.20

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32880 entries, 0 to 32879
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   city             32880 non-null  str
 1   state            32880 non-null  str
 2   observed_date    32880 non-null  object
 3   avg_temperature  32880 non-null  float64
 4   avg_feels_like   32880 non-null  float64
 5   avg_humidity     32880 non-null  float64
 6   avg_pressure     32880 non-null  float64
 7   avg_wind_speed   32880 non-null  float64
dtypes: float64(5), object(1), str(2)
memory usage: 2.0+ MB

In [5]:
df['observed_date'] = pd.to_datetime(df['observed_date'])

In [6]:
df['year_month'] = df['observed_date'].dt.strftime("%Y-%m")

In [7]:
monthly_avg_temp_city = pd.pivot_table(data=df, columns='year_month', index='city', values='avg_temperature')

In [8]:
monthly_avg_temp_city

year_month,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,...,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12
city,,,,,,,,,,,,,,,,,,,,,
Albuquerque,2.689355,3.920357,7.997742,13.786667,20.192903,24.667000,30.443226,26.917097,22.768333,16.086129,...,10.862581,15.373333,19.101935,26.226667,26.714839,27.212903,21.715667,16.697419,10.306333,6.835484
Anchorage,-5.425484,-6.679286,-4.269032,-0.328333,8.043871,12.605333,14.313871,14.473548,8.487667,1.853226,...,-0.235806,3.535000,8.724839,12.880333,16.234839,14.679677,10.001000,4.875484,-5.396333,-10.840645
Atlanta,9.745161,12.650714,13.417742,16.671000,19.840323,23.366000,26.612258,26.004516,22.471333,17.024516,...,14.256452,18.792333,20.569355,24.699333,27.168387,23.692903,23.371000,17.172258,12.946000,8.257097
Bellingham,5.737742,3.945357,6.397742,8.706000,15.197419,15.810667,18.750000,19.220645,15.275333,11.155806,...,7.756452,10.733333,13.235484,15.877667,18.184194,18.994839,16.331667,10.550000,8.056000,6.309355
Bend,0.164839,0.363571,1.016129,6.874667,13.843871,17.087000,22.243226,21.259032,14.659333,9.553226,...,4.888710,8.223667,12.697097,17.620667,22.061935,21.018710,17.795333,8.239032,6.519333,4.201290
Boise,1.043548,1.196786,3.605484,9.740333,18.396774,20.046667,27.855484,25.389032,19.784333,12.786129,...,8.474839,11.641667,17.453226,22.343667,26.432903,25.087742,21.710667,11.508387,8.097000,5.380968
Boston,2.648065,1.088571,4.380645,9.912000,15.218065,18.529333,24.115161,21.559677,18.980667,14.096452,...,5.335484,10.384333,14.830645,21.025333,24.739677,21.062903,18.084000,12.278710,5.475333,-1.176774
Bothell,5.824839,4.484643,6.458065,8.915000,16.247097,16.545000,19.974516,20.562903,15.941667,11.574839,...,8.145484,11.137000,13.804516,17.265667,19.910323,20.472581,17.521000,11.020968,8.743667,6.600968
Chicago,-0.541935,0.292857,2.273226,9.387333,13.612903,18.674333,21.687097,21.494194,18.377000,11.843871,...,5.497742,8.581667,12.221290,21.133667,23.588065,21.622581,18.830667,13.545484,5.207000,-3.074839
Dallas,11.368387,11.098929,15.922258,18.570000,24.249677,28.816333,32.142581,34.387742,29.327000,20.612903,...,17.886129,20.415333,23.326452,28.159333,29.475484,29.553226,27.066667,22.946774,17.161000,11.555806
Denver,-1.898387,0.478571,3.061613,9.406333,15.291935,18.503000,23.488387,22.865806,19.285333,11.045161,...,8.635484,10.288000,14.702258,21.435333,24.599677,23.120000,18.594333,12.191613,7.813667,5.923871
Honolulu,22.651935,22.333214,22.645484,22.961333,23.568710,24.977667,25.537097,25.867097,25.795667,25.220645,...,23.211613,23.333667,24.360968,25.240000,25.512258,26.199677,25.928000,25.395806,24.324667,23.099032
Houston,14.731613,15.285357,18.818387,19.693000,24.566774,27.862333,28.943226,30.337742,27.838333,21.506129,...,19.152581,22.101667,24.747097,27.318667,27.853871,28.100968,26.207667,23.262903,18.938000,14.709355
Kansas City,1.567742,3.303214,5.776774,13.695333,19.880645,24.455333,25.607742,25.653871,22.606333,14.775806,...,11.119677,14.300000,18.105806,24.549333,26.687097,24.186774,21.858333,17.162903,8.370333,2.271935
Las Vegas,8.210000,9.053929,12.069677,19.916000,25.972903,28.462333,36.753548,32.318065,27.325333,21.643548,...,15.669677,20.649000,26.128710,32.378667,33.668710,34.158065,28.471667,21.325484,15.902667,11.442258
Los Angeles,12.207419,12.335357,12.710323,15.827000,16.515806,18.140333,23.126774,23.265161,21.318000,20.025484,...,13.849677,15.805000,18.714516,20.293333,20.984516,23.446452,22.774667,19.209677,16.356667,15.252581
Miami,20.564516,22.236786,22.802903,24.163333,24.895161,27.049000,28.762581,28.746774,27.216333,25.190323,...,21.588710,23.839667,26.642903,27.464667,28.316774,28.369355,26.616333,25.585806,22.189000,21.717097
Minneapolis,-5.789032,-5.139643,-1.131935,7.649000,17.610968,23.283667,22.824194,23.036774,19.757333,10.634194,...,3.601613,8.580667,15.710323,20.508000,23.770968,21.511613,18.821667,12.471290,3.647000,-7.120323
New Orleans,15.686129,17.200000,19.157419,20.793333,24.986452,28.349000,29.289355,30.395806,27.072000,21.557097,...,18.561613,22.166000,24.495161,27.356333,28.021613,27.936452,26.586333,22.668065,17.715333,13.831290
New York,5.373871,4.200714,6.112903,13.320000,16.573871,20.374333,25.869677,23.850645,20.427667,15.450000,...,7.852258,12.646333,16.835484,23.227000,26.782258,22.782258,20.940667,14.403226,8.075333,0.573548
Olympia,5.392258,4.176786,5.561935,8.425667,15.676452,16.263667,19.604839,20.465806,15.689667,11.426129,...,7.868387,10.616333,13.468065,16.803333,19.558387,19.967097,17.173333,10.772258,8.694000,6.854516
Philadelphia,5.722581,5.273214,6.830323,14.535333,17.059677,21.025667,26.012903,24.407419,20.932333,15.569355,...,9.086774,13.763000,17.805484,23.254000,26.517419,22.681290,21.232000,14.828387,8.278000,0.732258
Phoenix,11.292258,13.126786,16.120645,23.275000,28.200000,31.398333,38.691613,36.346774,31.853667,26.687419,...,18.870323,22.993333,28.227097,34.103333,35.918387,36.520968,31.743000,24.852903,19.369333,15.865806
Portland,5.502258,4.158214,6.110000,9.633667,16.371613,17.251000,20.602258,21.223226,16.786333,12.880968,...,9.054516,11.689333,14.395161,17.216667,20.402258,20.949677,18.109333,11.781613,9.557667,8.049032
Salt Lake City,-0.628710,-1.280357,2.507097,9.403000,18.426452,20.689667,28.948387,25.282903,20.642667,11.893226,...,7.574194,11.716667,17.880645,24.515667,28.112258,26.400645,22.028667,12.055161,8.384667,5.838387
San Diego,12.881613,12.483929,12.844194,14.797333,16.038387,17.796333,20.837097,21.871613,21.064000,19.386452,...,14.068710,15.520667,17.420968,18.715333,20.171290,21.340968,21.920333,18.991935,16.518000,15.871935
San Francisco,9.980323,8.496786,9.189355,11.761000,13.226452,14.589000,15.813226,17.943226,16.713333,16.750645,...,11.602258,12.616333,14.597097,14.428333,15.255806,17.003548,18.212667,15.854194,13.036000,10.083548
Seattle,5.683871,4.333571,6.028710,8.307000,15.147419,15.576667,18.713871,19.254194,14.991667,11.360645,...,7.655484,10.181000,12.878710,16.190000,18.480000,18.964516,16.244000,10.571290,8.661667,6.552258
Spokane Valley,-0.477097,-0.872857,2.422258,7.014333,16.685161,18.597333,23.051613,21.927742,15.735000,9.482581,...,5.756452,9.176667,13.640000,19.064000,22.992258,22.723871,19.786000,8.402581,4.563667,2.467742
Yakima,0.604839,1.557857,4.948387,9.832333,19.544839,21.629000,25.747742,24.478710,17.880333,11.207097,...,8.471290,12.204333,16.622903,22.395667,26.035161,25.126452,20.956333,9.998710,5.860333,3.760000

In [9]:
month_day = df['observed_date'].dt.strftime("%m-%d")

In [10]:
conditions = [
    (month_day >= '09-22') & (month_day < '12-21'),
    (month_day >= '12-21') | (month_day < '03-20'),
    (month_day >= '03-20') & (month_day < '06-21'),
    (month_day >= '06-21') & (month_day < '09-22')
]

seasons = ['fall', 'winter', 'spring', 'summer']

In [11]:
df['season'] = np.select(conditions, seasons, default='unknown')

In [12]:
df['season'].value_counts(dropna=False)

season
spring    8370
summer    8370
fall      8100
winter    8040
Name: count, dtype: int64

In [13]:
def year_season(row):
    return row['season'].title() + " " + str(row['observed_date'].year)

In [14]:
df['season_year'] = df.apply(year_season, axis=1)

In [15]:
seasonal_avg_temp_city = pd.pivot_table(data=df, columns='season_year', index='city', values='avg_temperature')

In [16]:
seasonal_avg_temp_city

season_year,Fall 2023,Fall 2024,Fall 2025,Spring 2023,Spring 2024,Spring 2025,Summer 2023,Summer 2024,Summer 2025,Winter 2023,Winter 2024,Winter 2025
city,,,,,,,,,,,,
Albuquerque,11.351444,11.627333,12.605778,17.005376,18.624516,18.707634,27.351505,26.162258,25.960968,4.389101,5.839556,5.837865
Anchorage,-1.539778,-1.546667,-1.347667,5.031720,5.594301,6.689785,13.245376,13.356452,14.454086,-6.871573,-7.813889,-5.063933
Atlanta,13.890444,14.943444,13.950222,18.921828,20.352903,20.103763,25.318817,25.514946,25.047527,11.066517,8.984111,8.789551
Bellingham,8.676889,8.707000,9.605778,12.140860,11.471290,12.512903,18.105269,17.685161,17.909247,5.433596,5.486111,3.787528
Bend,6.502778,6.445556,7.869333,10.581398,10.211075,11.624624,20.189032,20.536989,20.442366,0.627191,1.348111,0.702921
Boise,8.592222,8.470444,9.781444,14.058925,14.180215,15.885914,24.737957,25.569247,24.618817,1.484382,3.297667,2.397416
Boston,8.712556,8.754444,7.849222,12.708710,13.206989,13.191935,22.282581,22.446129,21.863441,2.411461,1.212333,-0.687303
Bothell,8.798889,9.105778,10.128000,12.682581,12.024516,13.199462,19.333656,19.219785,19.427527,5.520225,5.925444,4.332584
Chicago,8.043889,8.677667,7.205556,11.828710,13.683441,11.727419,20.840323,21.747849,22.004946,0.703371,1.161000,-1.609663
Dallas,17.317111,18.791333,18.249111,22.252796,23.047742,22.782043,32.129462,30.117527,29.015484,11.915056,11.655333,10.812584
Denver,8.291444,8.710556,9.711000,12.254946,14.043978,13.963333,22.178602,23.455699,22.871075,0.242809,2.179778,1.496404
Honolulu,24.388444,24.534556,24.556556,23.642258,23.350108,24.086452,25.658710,25.345054,25.870538,22.371236,21.950556,22.498427
Houston,18.522333,20.382000,19.700333,22.905054,23.653763,23.902043,29.236989,27.823118,27.552473,15.413146,14.655333,14.021798
Kansas City,10.919000,11.225889,10.912333,17.081505,18.226559,17.161075,25.085269,24.833441,24.919355,3.207865,4.064667,1.477865
Las Vegas,16.905889,17.785444,17.851889,22.574516,24.412581,25.035054,32.520215,34.799677,32.529892,9.618764,10.938000,11.290674
Los Angeles,18.204444,16.837111,17.689778,16.077742,16.679677,17.671183,22.460538,22.908925,22.274731,12.581685,13.423444,13.691910
Miami,23.743000,24.271778,23.862333,24.795484,25.293763,25.310215,28.335376,28.420860,27.860323,21.440562,20.773889,20.443596
Minneapolis,6.645556,6.378778,5.392444,13.189892,12.761505,12.630645,22.442581,21.683226,21.834839,-3.660674,-1.055667,-5.332360
New Orleans,18.489111,20.079778,19.002778,23.461183,23.772581,23.686774,29.270108,28.213118,27.718495,16.462697,14.291333,14.007191
New York,10.673778,11.578778,9.989333,15.084946,15.436452,15.368495,23.993226,24.387527,24.126667,4.916180,3.753333,1.802472
Olympia,8.939556,9.127778,10.094889,12.162903,11.768710,12.771613,19.051613,18.852366,19.049570,5.041236,5.854889,4.309101
Philadelphia,10.748222,11.513000,10.130444,15.950000,16.771613,16.316344,24.300968,24.572473,24.070968,5.603933,4.500778,2.136517
Phoenix,22.064556,21.944778,21.279111,25.543656,26.622796,27.059032,35.921075,36.357742,35.300215,13.088764,14.173333,15.266404
Portland,10.202333,9.807000,11.019667,12.981398,12.668925,13.680860,19.978387,19.811075,19.909677,5.145393,6.139222,5.293258
Salt Lake City,8.113222,9.111778,10.066000,13.819462,14.781828,16.484301,25.351828,26.088602,25.814731,-0.008764,3.139778,3.070112
San Diego,17.703444,16.540222,17.640778,15.563871,16.181935,16.754731,21.117204,21.726022,20.910538,12.967753,13.810556,13.922360
San Francisco,14.419222,14.223556,13.756778,12.522903,13.730753,13.699785,16.579462,16.760108,16.412258,9.553708,11.118667,10.544382
Seattle,8.783778,8.957556,9.802000,11.887634,11.427097,12.288172,18.060430,18.255914,18.026129,5.327640,5.757778,4.398090
Spokane Valley,5.303222,5.909333,6.905000,12.286344,11.078710,12.744516,20.988280,21.834946,22.041183,-0.106742,0.760778,-0.543146
Yakima,7.153556,7.074667,8.293333,15.102581,14.301398,15.761828,23.683118,24.021505,24.507849,1.746517,2.572000,1.415955

In [31]:
def get_season(season):
    if season.lower() not in seasons:
        return "Input valid Season"
    return seasonal_avg_temp_city.loc[:, seasonal_avg_temp_city.columns[seasonal_avg_temp_city.columns.str.contains(season.title())]]
    
def get_year(year):
    return seasonal_avg_temp_city.loc[:, seasonal_avg_temp_city.columns[seasonal_avg_temp_city.columns.str.contains(str(year))]]

In [33]:
get_year(2024).loc['Bothell', :]

season_year
Fall 2024       9.105778
Spring 2024    12.024516
Summer 2024    19.219785
Winter 2024     5.925444
Name: Bothell, dtype: float64